# Generated by Django 6.0.3 on 2026-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_remove_giangvien_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='giangvien',
            name='role',
            field=models.CharField(default='teacher', max_length=20),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
