# Generated by Django 6.0.4 on 2026-04-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giangvien',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('khoa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sinhvien',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lop', models.CharField(max_length=100)),
            ],
        ),
    ]
